# Generated by Django 4.1.2 on 2022-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pregnancies", models.FloatField()),
                ("Glucose", models.FloatField()),
                ("BloodPressure", models.FloatField()),
                ("SkinThickness", models.FloatField()),
                ("Insulin", models.FloatField()),
                ("BMI", models.FloatField()),
                ("DiabetesPedigreeFunction", models.FloatField()),
                ("Age", models.FloatField()),
                ("classification", models.CharField(max_length=30)),
            ],
        ),
    ]
